/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinema.booking;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.util.Random;

/**
 *
 * @author init1
 */
public class movie extends javax.swing.JFrame {
    informations []movies = new informations[6];
    int SCALE_SMOOTH = Image.SCALE_SMOOTH;
     //private movies = new informations[6];
       
    /**
     * Creates new form movie
     */
    public movie() {
        initComponents();
       // jDateChooser1.get
       int count=0;
        
        movies[0]= new informations("./src/cinema/booking/images/past_lives.jpeg", "Past lives");
        movies[1]= new informations("./src/cinema/booking/images/blackstone.png", "Blackstone");
        movies[2]= new informations("./src/cinema/booking/images/chef.jpg", "Chef");
        movies[3]= new informations("./src/cinema/booking/images/la_haine.png", "La haine");
        movies[4]= new informations("./src/cinema/booking/images/magnetic_fields.jpg", "Magnetic fields");
        movies[5]= new informations("./src/cinema/booking/images/winona.png", "Winona");

        
        Color x = new Color (0X2C3E50);
        getContentPane().setLayout(null);
        getContentPane().setSize(1440, 1024);
        getContentPane().setBackground(x);
        
        jButton1.setText("SEARCH");
        jButton1.setBounds(565, 248, 311, 30);
        jButton1.setForeground(new Color(0XFFFFFF));
        jButton1.setBackground(new Color(0XE74C3C));
        jButton1.setFont(new Font("MV Boli",Font.PLAIN,20));
        jButton1.setBorder(BorderFactory.createBevelBorder(0));
        jButton1.setEnabled(true);
        
        jDateChooser1.setBounds(522, 174, 396, 37);
        
        jPanel1.setBackground(new Color(0X1E1E1E));
        jPanel1.setBounds(0, 448, 1440, 577);
        jPanel1.setLayout(null);
        
        
        jButton2.setBounds(82, 86, 252, 421);
        jButton2.setForeground(new Color(0XFFFFFF));
        jButton2.setBackground(new Color(0X363636));
        jButton2.setFont(new Font("MV Boli",Font.PLAIN,20));
        jButton2.setBorder(BorderFactory.createBevelBorder(0));
        jButton2.setHorizontalTextPosition(JButton.CENTER);
        jButton2.setVerticalTextPosition(JButton.BOTTOM);
        jButton2.setVisible(false);
        
        jButton3.setBounds(563, 86, 252, 421);
        jButton3.setForeground(new Color(0XFFFFFF));
        jButton3.setBackground(new Color(0X363636));
        jButton3.setFont(new Font("MV Boli",Font.PLAIN,20));
        jButton3.setBorder(BorderFactory.createBevelBorder(0));
        jButton3.setHorizontalTextPosition(JButton.CENTER);
        jButton3.setVerticalTextPosition(JButton.BOTTOM);
        jButton3.setVisible(false);
        
        jButton4.setBounds(1067, 86, 252, 421);
        jButton4.setForeground(new Color(0XFFFFFF));
        jButton4.setBackground(new Color(0X363636));
        jButton4.setFont(new Font("MV Boli",Font.PLAIN,20));
        jButton4.setBorder(BorderFactory.createBevelBorder(0));
        jButton4.setHorizontalTextPosition(JButton.CENTER);
        jButton4.setVerticalTextPosition(JButton.BOTTOM);
        jButton4.setVisible(false);
        
        jLabel1.setText("20:00-22:00");
        jLabel1.setHorizontalAlignment(JLabel.CENTER);
        jLabel1.setVerticalAlignment(JLabel.CENTER);
        jLabel1.setForeground(new Color(0XFFFFFF));
        jLabel1.setFont(new Font("MV Boli",Font.PLAIN,20));
        jLabel1.setVisible(true);
        jLabel1.setBounds(82, 0, 252, 83);
        
        jLabel2.setText("22:15-00:15");
        jLabel2.setHorizontalAlignment(JLabel.CENTER);
        jLabel2.setVerticalAlignment(JLabel.CENTER);
        jLabel2.setForeground(new Color(0XFFFFFF));
        jLabel2.setFont(new Font("MV Boli",Font.PLAIN,20));
        jLabel2.setVisible(true);
        jLabel2.setBounds(563, 0, 252, 83);
        
        jLabel3.setText("00:30-2:30");
        jLabel3.setBounds(1067, 0, 252, 83);
        jLabel3.setHorizontalAlignment(JLabel.CENTER);
        jLabel3.setVerticalAlignment(JLabel.CENTER);
        jLabel3.setForeground(new Color(0XFFFFFF));
        jLabel3.setFont(new Font("MV Boli",Font.PLAIN,20));
        jLabel3.setVisible(true);
        
        
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jDateChooser1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooser1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jDateChooser1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jDateChooser1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jDateChooser1InputMethodTextChanged(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.setEnabled(false);
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jButton2)
                .addGap(220, 220, 220)
                .addComponent(jButton4)
                .addContainerGap(721, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(491, 491, 491)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel1)
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jButton3)))
                        .addComponent(jLabel3))
                    .addContainerGap(491, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(16, 16, 16))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel2)
                    .addGap(8, 8, 8)
                    .addComponent(jLabel3)
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton3)
                        .addComponent(jLabel1))
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(132, 132, 132)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        new cinema().setVisible(true);
        getContentPane().setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        new cinema().setVisible(true);
        getContentPane().setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        new cinema().setVisible(true);
        getContentPane().setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
//        Random rand = new Random();
//        jButton2.setVisible(true);
//        jButton3.setVisible(true);
//        jButton4.setVisible(true);
//        int int1 = rand.nextInt(6);
//        int int2 = rand.nextInt(6);
//        int int3 = rand.nextInt(6);
//        int SCALE_SMOOTH = Image.SCALE_SMOOTH;
//        
//        jButton2.setText(movies[int1].getTitle());
//        ImageIcon icon1 = new ImageIcon(new ImageIcon(movies[int1].getImage()).getImage().getScaledInstance(225, 354, SCALE_SMOOTH ));
//        jButton2.setIcon(icon1);
//        jButton3.setText(movies[int2].getTitle());
//        ImageIcon icon3 = new ImageIcon(new ImageIcon(movies[int2].getImage()).getImage().getScaledInstance(225, 354, SCALE_SMOOTH ));
//        jButton3.setIcon(icon3);
//        jButton4.setText(movies[int3].getTitle());
//        ImageIcon icon4 = new ImageIcon(new ImageIcon(movies[int3].getImage()).getImage().getScaledInstance(225, 354, SCALE_SMOOTH ));
//        jButton4.setIcon(icon4);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jDateChooser1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooser1InputMethodTextChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jDateChooser1InputMethodTextChanged

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1StateChanged

    private void jDateChooser1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooser1CaretPositionChanged
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jDateChooser1CaretPositionChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(jDateChooser1.getDate()!=null ){
        Random rand = new Random();
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        int int1 = rand.nextInt(6);
        int int2 = rand.nextInt(6);
        int int3 = rand.nextInt(6);
        int SCALE_SMOOTH = Image.SCALE_SMOOTH;
        
        jButton2.setText(movies[int1].getTitle());
        ImageIcon icon1 = new ImageIcon(new ImageIcon(movies[int1].getImage()).getImage().getScaledInstance(225, 354, SCALE_SMOOTH ));
        jButton2.setIcon(icon1);
        jButton3.setText(movies[int2].getTitle());
        ImageIcon icon3 = new ImageIcon(new ImageIcon(movies[int2].getImage()).getImage().getScaledInstance(225, 354, SCALE_SMOOTH ));
        jButton3.setIcon(icon3);
        jButton4.setText(movies[int3].getTitle());
        ImageIcon icon4 = new ImageIcon(new ImageIcon(movies[int3].getImage()).getImage().getScaledInstance(225, 354, SCALE_SMOOTH ));
        jButton4.setIcon(icon4);
        Date date=jDateChooser1.getDate();
        
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateChooser1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser1AncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDateChooser1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
